version: '2'
services:
  web:
    build: .
    container_name: monolithic
    volumes:
      - ./:/web
    ports:
      - "3000:3000"
    links:
      - sidekiq_web
      - redis
    environment:
      - RAILS_SERVE_STATIC_FILES=true
    restart: always

  sidekiq_web:
    build: .
    volumes:
      - ./:/web
    command: bundle exec sidekiq
    restart: always
    links:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - PORT=6379
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
